export const ActionTypes = {
  ADD_VEHICLE: "ADD_VEHICLE",
  REMOVE_VEHICLE: "REMOVE_VEHICLE",
  SET_VEHICLE_LIST: "SET_VEHICLE_LIST",
  REMOVE_VEHICLE_LIST: "REMOVE_VEHICLE_LIST",
  SELECTED_VEHICLE: "SELECTED_VEHICLE",
  REMOVE_SELECTED_VEHICLE: "REMOVE_SELECTED_VEHICLE",
  UPDATE_VEHICLE: "UPDATE_VEHICLE",
};
